### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by andiukas** [Brunas/meteo_lt#9]
Esama temperatūra neatsinaujina daugiau nei 10val., perkrovus Ha atsinaujina į esamą

**Comment by Brunas** [comment]
@andiukas pabandykit 0.1.9. Pridėjau atskirą datą į atributus apie atnaujinimą. Vis gi, HASS nieko nekeičia atnaujinimo datų, jei realiai duomenyse niekas nesikeičia, o taip visai gali būt. Dabar po naujos datos pridėjimo, kaip ir pasikeičia atnaujinimo data.

**Comment by Brunas** [comment]
jau ir 0.2.0 išėjo, bet nesusiję ten pakeitimai

**Comment by Brunas** [comment]
Pasirodo, kad api.meteo.lt grąžina info neteisingai, įrodymas screen shot'e. 

<img width="1320" alt="Screenshot 2024-07-28 at 12 33 16" src="https://github.com/user-attachments/assets/0c9bc30a-9a76-49d4-87a0-43551f40b98a">

Vis gi, pabandysiu nufiltruot tai, kas per sena.

**Comment by andiukas** [comment]
> jau ir 0.2.0 išėjo, bet nesusiję ten pakeitimai

Nesimato šios versijos :)

**Comment by Brunas** [comment]
> > jau ir 0.2.0 išėjo, bet nesusiję ten pakeitimai
> 
> Nesimato šios versijos :)

Neskubėkite, bus dar nauja versija :)

**Comment by Brunas** [comment]
Pabandykit 0.2.2
